### ISSUE TITLE
Unchecked exception in render manager

### ISSUE THREAD

**Issue by ads103** [ThatRedox/ChunkyClPlugin#25]
When attempting to use the plugin, the following error occurs: 

Unchecked exception in render manager.
java.lang.NoSuchMethodError: se.llbit.chunky.block.Block.getTexture(I)Lse/llbit/chunky/resources/Texture;
	at chunkycl.GpuRayTracer.load(GpuRayTracer.java:328)
	at chunkycl.OpenClRenderer.render(OpenClRenderer.java:37)
	at se.llbit.chunky.renderer.DefaultRenderManager.run(DefaultRenderManager.java:313)

This happens when the Chunky status indicator reads, "Loading Block Textures into GPU: 2 of 4"

**Comment by ThatRedox** [comment]
This happens when you try and use the `2.4.X` build in `2.5.0` snapshots. Please use the newest development builds which target `2.5.0` or downgrade to `2.4.X`.
